name: Build .NET MAUI (.NET 9)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    name: iOS
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install iOS workload
        run: dotnet workload install maui-ios

      - name: Restore project
        run: |
          dotnet restore \
            /p:TargetFrameworks=net9.0-ios \
            /p:ExcludeMauiMacCatalyst=true

      - name: Build iOS
        run: |
          dotnet build -f net9.0-ios -c Release \
            /p:RuntimeIdentifier=ios-arm64 \
            /p:CodesignKey="" \
            /p:CodesignProvision="" \
            /p:BuildIpa=false

      - uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: "**/bin/Release/net9.0-ios/"
