name: Build .NET MAUI (.NET 9)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-android:
    name: Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore workload
        run: dotnet workload restore

      - name: Restore project
        run: dotnet restore

      - name: Build Android
        run: dotnet build -f net9.0-android -c Release

      - name: Publish Android
        run: dotnet publish -f net9.0-android -c Release -o publish

      - uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: publish/

  build-ios:
    name: iOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore workload
        run: dotnet workload restore

      - name: Restore project
        run: dotnet restore

      - name: Build iOS
        run: dotnet build -f net9.0-ios -c Release

      - uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: |
            **/bin/Release/net9.0-ios/

  build-windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore workload
        run: dotnet workload restore

      - name: Restore project
        run: dotnet restore

      - name: Build Windows
        run: dotnet build -f net9.0-windows10.0.19041.0 -c Release

      - name: Publish Windows
        run: dotnet publish -f net9.0-windows10.0.19041.0 -c Release -o publish

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: publish/
